# Site settings
title: Amsterdam Comics
email: info@amsterdamcomics.com
description: Asterdam Comics is a network of comics scholars in the Netherlands.
baseurl: ""
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
github_username:  gauthiier

# Build settings
markdown: kramdown

# Custom Variables
#navigation: true
