# Site settings
title: Amsterdam Comics
email: info@amsterdamcomics.com
description: Amsterdam Comics is an international network of comics scholars.
baseurl: ""
url: "http://amsterdamcomics.com" # the base hostname & protocol for your site
github_username:  gauthiier

# Build settings
markdown: kramdown

# Custom Variables
#navigation: true

#prose
prose:
  rooturl: ''
  siteurl: 'http://amsterdamcomics.com'
  relativeLinks: ''
  ignore:
    - _layouts
    - +++
    - .gitignore
    - CNAME
    - LICENSE
    - README.md
    - feed.xml
  media: 'img'  
